### ISSUE TITLE
Fill out _schema_def.py and address TODO's and FIXME's

### ISSUE THREAD

**Issue by geowurster** [SkyTruth/gpsdio#11]
Here's the naming convention I have been using:

```python
SCHEMA = {                  # Schema
    0.1: {                  # Version
        'mmsi': {           # Field
            'default': "",  # Attribute
            'good': 'name'  # Attribute
        }
    }
}
```

- [ ] Decide on a list of required attributes and add to all 
- [ ] Populate important attributes like good, bad, test, etc.
- [ ] Populate secondary attributes like units, description, etc.

**Comment by geowurster** [comment]
- [ ] Consider removing the keys `good` and `bad`.
- [ ] Consider renaming `test` to `validate`.

**Comment by geowurster** [comment]
Invalidated by #162.
